version: 2.1
orbs:
  pack: buildpacks/pack@0.2.4

executors:
  rust:
    machine:
      image: ubuntu-2004:202111-02

commands:
  restore-cargo-cache:
    steps:
      - restore_cache:
          keys:
            # CIRCLE_JOB is the job name, eg 'lint', ensuring caches are job-specific.
            - cargo-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.lock" }}-{{ checksum ".circleci/config.yml" }}
  save-cargo-cache:
    steps:
      - save_cache:
          key: cargo-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.lock" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - ~/.cargo
  install-rust:
    steps:
      - run:
          name: "Install Rust"
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
            chmod +x rustup.sh
            ./rustup.sh -y

jobs:
  lint:
    executor: rust
    steps:
      - checkout
      - restore-cargo-cache
      - install-rust
      - run:
          name: Clippy
          # Using --all-targets so tests are checked and --deny to fail on warnings.
          command: cargo clippy --all-targets --locked -- --deny warnings
      - run:
          name: rustfmt
          command: cargo fmt -- --check --verbose
      - save-cargo-cache

  test:
    executor: rust
    steps:
      - checkout
      - restore-cargo-cache
      - install-rust
      - pack/install-pack:
          version: 0.27.0
      - run:
          name: Install musl
          command: sudo apt-get update && sudo apt-get install musl-tools --no-install-recommends
      - run:
          name: Add musl target
          command: rustup target add x86_64-unknown-linux-musl
      # This can be removed when https://github.com/heroku/libcnb.rs/issues/407 is fixed.
      - run:
          name: Mark heroku/builder:22 as a trusted builder
          command: pack config trusted-builders add heroku/builder:22
      - run:
          name: Run tests
          command: cargo test --locked -- --include-ignored
      - save-cargo-cache

workflows:
  ci:
    jobs:
      - lint
      - test
