name: install-rust
runs:
  using: composite
  steps:
  - name: Install Rust
    run: |-
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
      chmod +x rustup.sh
      ./rustup.sh -y
    shell: bash