name: Buildpackage
on:
    release:
        types:
            - published
jobs:
    create-package:
        name: Package, Publish, and Register
        runs-on:
            - ubuntu-latest
        steps:
            - id: checkout
              name: Checkout code
              uses: actions/checkout@v2
            - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
              name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                registry: docker.io
                username: ${{ secrets.DOCKER_HUB_USER }}
                password: ${{ secrets.DOCKER_HUB_PASS }}
            - id: pack
              name: Setup Pack CLI
              uses: buildpacks/github-actions/setup-pack
              with:
                version: "0.14.1"
            - id: package
              name: Package Buildpack
              run: |
                #!/usr/bin/env bash
                set -euo pipefail

                VERSION="$(cat buildpack.toml | yj -t | jq -r .buildpack.version)"
                pack package-buildpack --config package.toml --publish ${PACKAGE}:${VERSION}
                DIGEST="$(crane digest ${PACKAGE}:${VERSION})"

                echo "::set-output name=version::$VERSION"
                echo "::set-output name=digest::$DIGEST"
              shell: bash
              env:
                PACKAGE: docker.io/heroku/procfile-cnb
            - id: register
              name: Register Buildpack
              uses: docker://ghcr.io/buildpacks/actions/registry
              with:
                token:   ${{ secrets.PUBLIC_REPO_TOKEN }}
                id:      heroku/procfile
                version: ${{ steps.package.outputs.version }}
                address: docker.io/heroku/procfile-cnb@${{ steps.package.outputs.digest }}
