name: Release
on:
    release:
        types:
            - published
jobs:
    create-package:
        name: Package, Publish, and Register
        runs-on:
            - ubuntu-latest
        steps:
            - id: checkout
              name: Checkout code
              uses: actions/checkout@v2
            - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
              name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                registry: docker.io
                username: ${{ secrets.DOCKER_HUB_USER }}
                password: ${{ secrets.DOCKER_HUB_PASS }}
            - uses: actions/setup-go@v2
              with:
                go-version: '^1.12.1'
            - id: setup-pack
              name: Install Pack
              uses: buildpacks/github-actions/setup-pack@v4.2.0
            - id: compile
              name: Compile Buildpack
              run: |
                #!/usr/bin/env bash
                set -euo pipefail
                make build
                make test
            - id: package
              name: Package Buildpack
              run: |
                #!/usr/bin/env bash
                set -euo pipefail
                VERSION="$(cat buildpack.toml | yj -t | jq -r .buildpack.version)"
                pack package-buildpack --publish ${PACKAGE}:${VERSION}
                DIGEST="$(crane digest ${PACKAGE}:${VERSION})"
                echo "::set-output name=version::$VERSION"
                echo "::set-output name=address::${PACKAGE}@${DIGEST}"
              shell: bash
              env:
                PACKAGE: docker.io/heroku/procfile-cnb
            - id: register
              name: Register Buildpack
              uses: docker://ghcr.io/buildpacks/actions/registry/request-add-entry:4.2.0
              with:
                token:   ${{ secrets.PUBLIC_REPO_TOKEN }}
                id:      heroku/procfile
                version: ${{ steps.package.outputs.version }}
                address: ${{ steps.package.outputs.address }}
